# Generated by Django 4.2.7 on 2023-11-20 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_service_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkGalllery',
            new_name='WorkGallery',
        ),
    ]
